version: '2.1'

services:

  rabbitmq:
    image: rabbitmq
    build: ./queue
    ports:
        - "15672:15672"
        - "5672:5672"
    restart: always

  redis:
    container_name: redis
    image: redis
    ports:
     - "6379:6379"
    healthcheck:
      test: exit 0

  # ----------------------------------------
  # ----------------------------------------
  # Users service configuration
  # ----------------------------------------
  # ----------------------------------------

  users-service-db:
    container_name: users-service-db
    build: ./UsersService/db
    ports:
      - 5432:5432  # expose ports - HOST:CONTAINER
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0

  usersservice:
    image: usersservice
    build: ./UsersService
    environment:
      - APP_RD_ADDRESS=redis:6379
      - APP_RD_AUTH=password
      - APP_RD_DBNAME=0
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@users-service-db:5432/users_prod?sslmode=disable
      - DATABASE_DEV_URL=postgresql://postgres:postgres@users-service-db:5432/users_dev?sslmode=disable
      - DATABASE_TEST_URL=postgresql://postgres:postgres@users-service-db:5432/users_test?sslmode=disable
    depends_on:
      users-service-db:
        condition: service_healthy
      redis:
        condition: service_healthy
    links:
      - users-service-db
      - redis

  # ----------------------------------------
  # ----------------------------------------
  # News Orchestrator service configuration
  # ----------------------------------------
  # ----------------------------------------

  orcherstrator_news_service:
    image: orcherstrator_news_service
    build: ./NewsOrcherstrator
    volumes:
      - './NewsOrcherstrator:/app'
    environment:
      - APP_SETTINGS=config.DevelopmentConfig
      - QUEUE_HOST=amqp://guest:guest@rabbitmq
    depends_on:
      - famous_news_service
      - rabbitmq
    links:
      - famous_news_service
      - rabbitmq

  # ----------------------------------------
  # ----------------------------------------
  # Famous service configuration
  # ----------------------------------------
  # ----------------------------------------

  querydb_famous:
    image: querydb_famous
    build: ./FamousNewsService/query_db/
    ports:
      - "5433:5432"
    restart: always

  commanddb_famous:
    image: commanddb_famous
    build: ./FamousNewsService/command_db/
    ports:
      - "27017:27017"
    restart: always
    healthcheck:
      test: exit 0

  famous_news_service:
    image: famous_news_service
    build: ./FamousNewsService
    volumes:
      - './FamousNewsService:/app'
    environment:
      - QUERYBD_HOST=mongodb://querydb_famous:27017/
      - QUEUE_HOST=amqp://guest:guest@rabbitmq
      - COMMANDDB_HOST=postgresql://postgres:postgres@commanddb_famous:5432/news_prod?sslmode=disable
      - COMMANDDB_DEV_HOST=postgresql://postgres:postgres@commanddb_famous:5432/news_dev?sslmode=disable
      - COMMANDDB_TEST_HOST=postgresql://postgres:postgres@commanddb_famous:5432/news_test?sslmode=disable
    depends_on:
      - querydb_famous
      - commanddb_famous
      - rabbitmq
    links:
      - querydb_famous
      - commanddb_famous
      - rabbitmq


  # ----------------------------------------
  # ----------------------------------------
  # Politics service configuration
  # ----------------------------------------
  # ----------------------------------------

  querydb_politics:
    image: querydb_politics
    build: ./PoliticsNewsService/query_db/
    ports:
      - "5434:5432"
    restart: always

  commanddb_politics:
    image: commanddb_politics
    build: ./PoliticsNewsService/command_db/
    ports:
      - "27018:27017"
    restart: always
    healthcheck:
      test: exit 0

  politics_news_service:
    image: politics_news_service
    build: ./PoliticsNewsService
    volumes:
      - './PoliticsNewsService:/app'
    environment:
      - QUERYBD_HOST=mongodb://querydb_politics:27017/
      - QUEUE_HOST=amqp://guest:guest@rabbitmq
      - COMMANDDB_HOST=postgresql://postgres:postgres@commanddb_politics:5432/news_prod?sslmode=disable
      - COMMANDDB_DEV_HOST=postgresql://postgres:postgres@commanddb_politics:5432/news_dev?sslmode=disable
      - COMMANDDB_TEST_HOST=postgresql://postgres:postgres@commanddb_politics:5432/news_test?sslmode=disable
    depends_on:
      - querydb_politics
      - commanddb_politics
      - rabbitmq
    links:
      - querydb_politics
      - commanddb_politics
      - rabbitmq


  # ----------------------------------------
  # ----------------------------------------
  # Sports service configuration
  # ----------------------------------------
  # ----------------------------------------

  querydb_sports:
    image: querydb_sports
    build: ./SportsNewsService/query_db/
    ports:
      - "5435:5432"
    restart: always

  commanddb_sports:
    image: commanddb_sports
    build: ./SportsNewsService/command_db/
    ports:
      - "27019:27017"
    restart: always
    healthcheck:
      test: exit 0

  sports_news_service:
    image: sports_news_service
    build: ./SportsNewsService
    volumes:
      - './SportsNewsService:/app'
    environment:
      - QUERYBD_HOST=mongodb://querydb_sports:27017/
      - QUEUE_HOST=amqp://guest:guest@rabbitmq
      - COMMANDDB_HOST=postgresql://postgres:postgres@commanddb_sports:5432/news_prod?sslmode=disable
      - COMMANDDB_DEV_HOST=postgresql://postgres:postgres@commanddb_sports:5432/news_dev?sslmode=disable
      - COMMANDDB_TEST_HOST=postgresql://postgres:postgres@commanddb_sports:5432/news_test?sslmode=disable
    depends_on:
      - querydb_sports
      - commanddb_sports
      - rabbitmq
    links:
      - querydb_sports
      - commanddb_sports
      - rabbitmq


  # ----------------------------------------
  # ----------------------------------------
  # Recommendation service configuration
  # ----------------------------------------
  # ----------------------------------------

  recommendation_db:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "none"

  recommendation_service:
    image: recommendation_service
    build: ./RecommendationService
    volumes:
      - './RecommendationService:/app'
    environment:
      - APP_SETTINGS=config.DevelopmentConfig
      - QUEUE_HOST=amqp://guest:guest@rabbitmq
    depends_on:
      - recommendation_db
      - rabbitmq
    links:
      - recommendation_db
      - rabbitmq

  # ----------------------------------------
  # ----------------------------------------
  # NGINX configuration
  # ----------------------------------------
  # ----------------------------------------

  proxy:
    container_name: loadbalance
    build: ./nginx
    ports:
      - "80:80"
    links:
      - usersservice
      - orcherstrator_news_service
